@baseUrl = http://localhost:8080

@apiKey = {{createAccount.response.body.api_key}}
@accountId = {{createAccount.response.body.id}}

### creates a new account
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe4",
    "email": "john.doe4@example.com"
}

### get account by api key
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}

### get account by id
GET {{baseUrl}}/accounts/{{accountId}}


### creates a new invoice
# @name createInvoice
POST {{baseUrl}}/invoices
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "amount": 1000,
    "description": "Test Invoice",
    "payment_type": "credit_card",
    "card_number": "1234567890123456",
    "expiry_month": 12,
    "expiry_year": 2025,
    "cvv": "123"
}

@invoiceId = {{createInvoice.response.body.id}}
### get invoice by id

GET {{baseUrl}}/invoices/{{invoiceId}}
X-API-Key: {{apiKey}}

### get all invoices
GET {{baseUrl}}/invoices
X-API-Key: {{apiKey}}


